### PR TITLE
RELEASES: Use an asterix bullet for "Minor and patch releases..."

### PR DESCRIPTION
**Pull request by wking**
Picking up Ma Shimiao's [change][1] from opencontainers/runtime-spec#937, this gives us consistent bullet characters for all items in this list.

[1]: https://github.com/opencontainers/runtime-spec/pull/937/files#diff-5cafcf46bfb947f8e58fa5c16d39018cL49

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM

**Comment by caniszczyk** [comment]
LGTM

**Comment by wking** [comment]
Ah, nice to see that #29 works, and a maintainer vote counts for each project they maintain :).

**Comment by wking** [comment]
selinux has the smallest maintainer set.  @mrunalp, @rhatdan, @runcom, can you take a look?  If two of you LGTM, we should be mostly there.

**Pull request merged**
