### PR TITLE
Test PullApprove

### PR DESCRIPTION
**Pull request by caniszczyk**

### CODE REVIEW

**Comment by caniszczyk** [comment]
cc: @crosbymichael

**Comment by caniszczyk** [comment]
LGTM

**Comment by caniszczyk** [comment]
magic... cc: @crosbymichael

**Comment by wking** [comment]
The logic you're using [1] doesn't match the docs [2].  Is it just up
to admins to keep a team in sync with the MAINTAINERS file for each
repository/project?  Or is it worth updating the guide to cite the
appropriate GitHub team?

[1]: https://github.com/opencontainers/project-template/blob/560fdc9f479892138fc8d449b36aded1bbe0f57d/.pullapprove.yml#L6-L8
[2]: https://github.com/opencontainers/project-template/blame/560fdc9f479892138fc8d449b36aded1bbe0f57d/MAINTAINERS_GUIDE.md#L66

**Comment by crosbymichael** [comment]
@caniszczyk nice, let me read up on this, it looks really nice and promising

**Comment by crosbymichael** [comment]
LGTM

**Comment by caniszczyk** [comment]
@crosbymichael looks like it worked :)

**Comment by caniszczyk** [comment]
This works, closing PR.

**Pull request closed without merging**
