### PR TITLE
adding security and CoC links

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

https://github.com/opencontainers/org/issues/3

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by cyphar** [comment]
o.O

2019-02-27-115555_593x70_scrot

**Comment by cyphar** [comment]
LGTM.

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
omg, pullapprove is confus 
image

It's requiring approval of all the _groups_ ? @caniszczyk have you seen that before?

**Comment by cyphar** [comment]
I think there's some weird configuration in place for project-template but it's just *ridiculous* to require 2 LGTMs from *every* group -- especially some groups like @opencontainers/selinux-maintainers which only has 3 people in it.

**Comment by vbatts** [comment]
*quorum*

**Comment by vsoch** [comment]
Code of conduct link is updated to be outside of .github (and in all caps) to reflect OCI call discussion.

**Comment by vbatts** [comment]
LGTM

**Pull request closed without merging**
