### PR TITLE
Add governance and releases docs

### PR DESCRIPTION
**Pull request by philips**
This is a proposed process for approval of new releases of
specifications and projects from the OCI.

The creation of this process is designed to clarify how a release gets
created and who needs to sign off.

Replaces https://github.com/opencontainers/tob/pull/15

### CODE REVIEW

**Comment by philips** [comment]
Closing this as there are outdated comments from @wking that are added.

**Comment by vbatts** [comment]
@philips is this ready for review?

**Comment by wking** [comment]
On Mon, Jul 18, 2016 at 04:40:09PM -0700, Vincent Batts wrote:
> @philips is this ready for review?

This is being actively voted on [1].  If you have issues with it, you
should start campaining for REJECTs in that thread.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/x-Oh3PDz1Y8

**Comment by vbatts** [comment]
oh right. I didn't put the two together.

**Comment by philips** [comment]
LGTM 

@caniszczyk can you LGTM this so we can merge it. The vote passed: https://groups.google.com/a/opencontainers.org/d/msg/dev/x-Oh3PDz1Y8/q7t2IseVAwAJ

**Comment by caniszczyk** [comment]
LGTM

**Comment by wking** [comment]
This series is not consistently Signed-off-by.  Maybe squash down to a
single commit before merging?  I'm fine if I don't get listed as a
co-author, but you can add my Signed-off-by to the squashed commit.

**Comment by philips** [comment]
@wking I would rather just merge this as-is even though the signed-off-by's are missing. I can certainly squash. @caniszczyk do you mind merging it as-is?

**Comment by wking** [comment]
On Thu, Jul 21, 2016 at 01:10:16PM -0700, Brandon Philips wrote:
> @wking I would rather just merge this as-is even though the
> signed-off-by's are missing.

Since it's just your commits without the Signed-off-by's, maybe the
lawyers (do we actually have any OCI lawyers recommending the DCO and
Signed-off-by?) would be happy with you Signed-off-by'ing the merge
commit?

**Comment by caniszczyk** [comment]
Next step is to copy these over to runc/runtime-spec/image-spec repos

**Comment by wking** [comment]
On Thu, Jul 21, 2016 at 03:29:24PM -0700, Chris Aniszczyk wrote:
> Next step is to copy these over to runc/runtime-spec/image-spec
> repos

Where are we with #4?  It would be nice if after an all-maintainer
vote we could tally a particular Project (e.g. runtime-spec), see that
the motion passed with those maintainers, run:

  $ git pull git://github.com/opencontainers/project-template.git

in runtime-spec and push it to master without bothering with
second-round PRs.  But that's not going to work unless everything in
project-template has been approved by the target Project's
maintainers.

**Pull request merged**
